### ISSUE TITLE
feature-request: Support for multiple suggestions

### ISSUE THREAD

**Issue by computnik** [muenzpraeger/eslint-plugin-inclusive-language#17]
---
| Type    | Title                             | About                                                                                                                     |
|---------|----------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| Feature | Support for multiple suggestions | _Allowing configuration for one or more suggestions as alternatives to be used in place of words for inclusive language._ |

### Problem Description
Usually in enterprises, when configuring & using across multiple projects, sometimes it would make sense to provide multiple suggestions for developers to use as alternatives for the words, to have more inclusive codebase.

### Proposed Solution
Instead of using one suggestion, multiple words can be used as suggestions in form of an array.

**Comment by muenzpraeger** [comment]
Will be released with v2.0.0.
