### ISSUE TITLE
JSX text nodes support

### ISSUE THREAD

**Issue by DimaSerhin** [muenzpraeger/eslint-plugin-inclusive-language#43]
## JSX support

Hello. Thanks for creating this plugin. 

Currently I am using it in typescript app generated via create-react-app and it seems like any text node inside jsx are not linted.

I am wondering if this is something related to my setup or jsx text nodes are not supported.
## Example

<img width="472" alt="Screen Shot 2021-06-07 at 16 37 49" src="https://user-images.githubusercontent.com/10065317/121026342-e2252000-c75a-11eb-8f77-9f6d221e3088.png">

**Comment by muenzpraeger** [comment]
JSX parsing comes from the [JSX parser in ESLint](https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options). From what it looks like you're correct, it doesn't seem to support text nodes. As that's built-in functionality provides as-is there's not much I can do.
