### ISSUE TITLE
Working with vuejs/nuxt

### ISSUE THREAD

**Issue by MrZyr0** [muenzpraeger/eslint-plugin-inclusive-language#48]
Hello everyone 👋 

I am very interested in this plugin for my open-source project [SCT](https://github.com/SCT-devTeam).

I want to use it for the frontend, which uses Nuxt.Js 2, but eslint does nothing.

Here is an example using the string "hey guys" as a test:
The file `index.vue` | The console output using <br/>`eslint --ext \".js,.vue\" --ignore-path .gitignore .`
------------ | -------------
![Capture d’écran 2021-10-23 à 12 34 26](https://user-images.githubusercontent.com/32927775/138552691-c02e1d48-3704-4e26-896c-0e39c5a7636c.png) | ![image](https://user-images.githubusercontent.com/32927775/138552713-85a0147f-825c-484a-917c-6e68435f9c2a.png)

**Comment by muenzpraeger** [comment]
Hey - there are a couple of things:

- The plugin validates JS code, so it won't look into the `template` section of your `.vue` file
- In your example you have the non-inclusive word as part of a string literal. Testing on this is per default `off`, you can enable it with a [custom configuration](https://github.com/muenzpraeger/eslint-plugin-inclusive-language/blob/primary/docs/rules/use-inclusive-words.md#enable-string-value-linting).

If you for example add `const theMaster = 'test';`, that will give a linting warning out-of-the-box.

**Comment by MrZyr0** [comment]
Hey, sorry for the late reply.

I don't really understand why your plugin doesn't look in strings 🤔. 
Does it mean that the plugin is only useful for developers who want more inclusive code?
But it doesn't impact the result for the client at all?

**Comment by muenzpraeger** [comment]
As mentioned before, you can lint for strings by enabling a custom configuration.

And I also mentioned that this plugin validates JavaScript code (because ESlint is a JavaScript linter). For other file types you've to investigate the usage of a custom parser for ESlint, like [vue-eslint-parser](https://www.npmjs.com/package/vue-eslint-parser).

**Comment by MrZyr0** [comment]
hummm okay, thank you for your precision.

Sorry for the inconvenience
