### ISSUE TITLE
Update to support eslint 8

### ISSUE THREAD

**Issue by ticklemepierce** [muenzpraeger/eslint-plugin-inclusive-language#49]
eslint 8 introduced a breaking change for rules that offer suggestions/fixes.  https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#suggestions
 
I know that this repo does suggestions.  I believe it does fixes as well, however I have not looked in depth yet.

Anyways, we are using this in a few of our company's repos, and would love to implement in more.  Some repos are already on eslint 8, however, meaning we currently can't add to all JS repos that we have.

**Comment by muenzpraeger** [comment]
Releasing v2.2.0 now
