### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by cgatian** [muenzpraeger/eslint-plugin-inclusive-language#55]
:rip:?

**Comment by muenzpraeger** [comment]
Nope.

What should change?

**Comment by cgatian** [comment]
Looks like there's open PRs that haven't moved.

**Comment by cgatian** [comment]
Also thanks for the reply. Glad it hasn't gone dormant

**Comment by muenzpraeger** [comment]
Good points with the PRs - there wasn't much movement b/c the configurability offers already a lot of options on how to use the plugin.

I'll take a look at the issues/PRs in the next couple of days. Thanks for the reminder!
