### ISSUE TITLE
feat: Allow inline configuration in addition to JSON files

### ISSUE THREAD

**Issue by sarayourfriend** [muenzpraeger/eslint-plugin-inclusive-language#7]
Currently the only way to pass additional configuration is by passing a JSON file path. However, this means that folks have to introduce another configuration file to their projects, even for the smallest changes to the default configuration. It also means that it is not possible to run JavaScript over the config if using `.eslintrc.js`.

It should be simple enough to change the [`customRuleConfig`](https://github.com/muenzpraeger/eslint-plugin-inclusive-language/blob/primary/lib/rules/use-inclusive-words.js#L18) function to just return the parameter if it's an object and to only construct a path for and parse JSON when it is a string.

This would also ease testing different configurations as the configurations could live inline with the tests rather than needing multiple files.

**Comment by muenzpraeger** [comment]
Good idea. At the end it'll be anyway a fatigue - either a long `eslint` config file or yet another config file. ;-)

I'm taking a stab via #9.

**Comment by muenzpraeger** [comment]
@saramarcondes v1.2.0 published to npm! Thanks again for the contribution!
